name: sports_talent_assessment
description: "AI-Powered Sports Talent Assessment App - Revolutionizing talent discovery in rural India"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Network & API
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  
  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Camera & Video
  camera: ^0.10.5+5
  video_player: ^2.7.2
  video_compress: ^3.1.2
  image_picker: ^1.0.4
  
  # AI/ML & Computer Vision
  tflite_flutter: ^0.10.4
  image: ^4.1.3
  
  # UI & Animations
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Utilities
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1
  path: ^1.8.3
  
  # Date & Time
  intl: ^0.18.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
    - assets/models/pose_detection/
    - assets/models/sports_analysis/
    - assets/benchmarks/
  
  # Fonts will be added later when needed
