// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
// coverage:ignore-file

import 'package:get_it/get_it.dart' as _i1;
import 'package:injectable/injectable.dart' as _i2;

import '../../core/network/network_client.dart' as _i3;

/// A callable class that can be used to configure the injectable dependencies
/// This will be generated by the injectable package
@_i2.InjectableInit()
_i1.GetIt $initGetIt(
  _i1.GetIt getIt, {
  String? environment,
  _i2.EnvironmentFilter? environmentFilter,
}) {
  final gh = _i2.GetItHelper(
    getIt,
    environment,
    environmentFilter,
  );
  
  // Register NetworkClient
  gh.lazySingleton<_i3.NetworkClient>(() => _i3.NetworkClient());
  
  return getIt;
}
